import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolve(repositoryRoot, "src");
const targetRoot = resolve(repositoryRoot, "sharepoint", "sol-dms", "src", "solDmsApp");
const expectedParent = resolve(repositoryRoot, "sharepoint", "sol-dms", "src");

if (dirname(targetRoot) !== expectedParent || !targetRoot.endsWith(`${sep}solDmsApp`)) {
  throw new Error(`Refusing to synchronise to unexpected target: ${targetRoot}`);
}

if (!existsSync(resolve(repositoryRoot, "sharepoint", "sol-dms", "package.json"))) {
  throw new Error("The SPFx package has not been scaffolded.");
}

if (existsSync(targetRoot)) rmSync(targetRoot, { recursive: true, force: true });
mkdirSync(targetRoot, { recursive: true });

const includedDirectories = ["app", "components", "domain", "services", "styles"];
const excludedFiles = new Set(["services/runtime.ts", "services/demo.ts"]);

for (const directory of includedDirectories) {
  const source = join(sourceRoot, directory);
  const target = join(targetRoot, directory);
  cpSync(source, target, {
    recursive: true,
    filter(path) {
      const key = relative(sourceRoot, path).replaceAll("\\", "/");
      if (excludedFiles.has(key)) return false;
      return !key.endsWith(".test.ts") && !key.endsWith(".test.tsx");
    },
  });
}

// SPFx compiles imported styles as CSS modules, but the application markup uses
// stable semantic class names. Generate one module that explicitly exports the
// verified application styles to global scope so css-loader cannot rename them.
const globalStyles = ["tokens.css", "app.css"]
  .map((fileName) => readFileSync(join(sourceRoot, "styles", fileName), "utf8"))
  .join("\n\n");
const globalStyleModule = [
  "// Generated by scripts/sync-spfx.mjs. Do not edit this file directly.",
  "// The standalone styles remain authoritative for both application hosts.",
  ":global {",
  globalStyles
    .split(/\r?\n/u)
    .map((line) => line.length > 0 ? `  ${line}` : "")
    .join("\n"),
  "}",
  "",
].join("\n");
writeFileSync(
  resolve(expectedParent, "webparts", "solDms", "components", "SolDms.module.scss"),
  globalStyleModule,
  "utf8",
);

const copied = readdirSync(targetRoot, { recursive: true }).length;
process.stdout.write(`Synchronised ${copied} SOL DMS application entries into the SPFx build tree.\n`);
